services:
  vm1:
    build:
      context: .
      args:
        CONFIG_DIR: vm1
        CA_DIR: /root/planetCA
        MAIL_HOSTNAME: mail.planet.edu
    container_name: vm1
    privileged: true
    networks:
      vnet1:
        ipv4_address: 192.168.102.10
  
  vm2:
    build:
      context: .
      args:
        CONFIG_DIR: vm2
        MAIL_HOSTNAME: mail.zone02.org
    container_name: vm2
    privileged: true
    networks:
      vnet1:
        ipv4_address: 192.168.102.20


networks:
  vnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.102.0/24
          gateway: 192.168.102.1